### ISSUE TITLE
Amazon EMR上のSpark SQLでcsvが読み込めない

### ISSUE THREAD

**Issue by jurin-n** [jurin-n/sandbox#1]
### 該当コード
```
df5 = ss.read.csv('s3n://${.csv格納用に作ったバケット}/batchAnalysticsData_train_5.csv', header=True, encoding='UTF-8',schema=struct)
```

### エラーメッセージ
```
'java.lang.RuntimeException: java.lang.RuntimeException: Unable to instantiate org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient;'
Traceback (most recent call last):
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 441, in csv
    return self._df(self._jreader.csv(self._spark._sc._jvm.PythonUtils.toSeq(path)))
  File "/usr/lib/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 69, in deco
    raise AnalysisException(s.split(': ', 1)[1], stackTrace)
pyspark.sql.utils.AnalysisException: 'java.lang.RuntimeException: java.lang.RuntimeException: Unable to instantiate org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient;'
```

#### 構成の詳細
* リリースラベル:emr-5.17.0
* Hadoop ディストリビューション:Amazon 2.8.4
* アプリケーション:JupyterHub 0.8.1, Spark 2.3.1

**Comment by jurin-n** [comment]
Amazon EMR環境の構成にHive入れなかったのダメだった？

**Comment by jurin-n** [comment]
ソフトウェア設定にHive 2.3.3を追加したら解決。
よって、構成の詳細は下記のようになった。
### 構成の詳細
* リリースラベル:emr-5.17.0
* Hadoop ディストリビューション:Amazon 2.8.4
* アプリケーション:JupyterHub 0.8.1, **_Hive 2.3.3_** ,Spark 2.3.1
